### ISSUE TITLE
Please, provide links to dependent libraries

### ISSUE THREAD

**Issue by Drugoy** [HotKeyIt/ObjTree#1]
ObjTree depends on some libraries.
One of them is mentioned as `#include *i <LV>` (`*i` makes it optional, but the lib is still mentioned without a link to it).
The other one is not even mentioned, I had to search for the non-existent function's name (`Attach(…)`) to find <a href="http://www.autohotkey.net/~HotKeyIt/LibV1/Attach.ahk">it</a> (and it's not even in any of your GitHub repos).
Please, provide links to get those libraries and mention that at least in README.
Thanks in advance.

**Comment by HotKeyIt** [comment]
I have added the functions
